name: Build and test

on:
  push:
    tags:
      - "*"

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false

  build_singularity_and_upload:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3

    - name: Get version
      id: get_version
      run: |
        echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Create singularity image
      id: create_image
      run: |
        cd projects/singularity
        PACKAGE=revbayes-${{ steps.get_version.outputs.version }}-linux64-singularity.simg
        singularity build --fakeroot ~/${PACKAGE} Singularity
        echo ::set-output name=archive_name::${PACKAGE}
        echo ::set-output name=archive_path::${HOME}/${PACKAGE}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ${{ steps.create_image.outputs.archive_path }}
        asset_name: ${{ steps.create_image.outputs.archive_name }}
        asset_content_type: application/octet-stream

  build_and_upload:
    needs: create_release
    strategy:
      matrix:
        name: [ubuntu-gcc-9,
               macos-xcode-12.5,
               windows
               ]

        include:
          - name: ubuntu-gcc-9
            os: ubuntu-latest
            compiler: gcc
            version: "9"
            mpi: false
            arch: "linux64"

          - name: macos-xcode-12.5
            os: macos-latest
            compiler: xcode
            version: "12.5"
            mpi: false
            arch: "mac64"
  
          - name: windows
            os: ubuntu-latest
            compiler: idk
            version: "9000"
            mpi: false
            arch: "win64"


    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install (Linux)
      if: runner.os == 'Linux' && matrix.name != 'windows'
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc libcairo2-dev ccache libopenlibm-dev
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          sudo apt-get install -y g++-${{ matrix.version }}
          echo "C_COMPILER=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX_COMPILER=g++-${{ matrix.version }}" >> $GITHUB_ENV
        else
          sudo apt-get install -y clang-${{ matrix.version }}
          echo "C_COMPILER=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX_COMPILER=clang++-${{ matrix.version }}" >> $GITHUB_ENV
        fi
        if [ "${{ matrix.mpi }}" = true ] ; then
          sudo apt-get install libopenmpi-dev
        fi

    - name: Install (macOS)
      if: runner.os == 'macOS'
      run: |
          rm -rf /usr/local/bin/2to3 
          
          brew update
          brew install pkg-config pandoc boost ccache coreutils openlibm
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
          ccache --set-config=cache_dir=$HOME/.ccache

    - name: Install (Windows meson cross compile)
      if: matrix.name == 'windows'
      run: |
          sudo apt-get update
          sudo apt-get install -y pandoc libcairo2-dev ccache dos2unix zstd
          sudo apt-get install git python3-setuptools python3-pip g++-mingw-w64 wine64
          sudo -H pip3 install meson
          sudo -H pip3 install ninja

    # Caches for different branches are isolated, so we don't need to put the branch name into the key.
    # The total size for all caches in a repository is 5Gb.

    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      run: |
        if [ "$RUNNER_OS" = "Linux" ] ; then
          stamp=$(date '+%s')
        else
          stamp=$(gdate '+%s')
        fi
        echo "${stamp}"
        echo "::set-output name=timestamp::${stamp}"

    - name: ccache cache files
#      uses: actions/cache@v2
#     We want to cache the build artifacts whether or not the tests succeed.
      uses: pat-s/always-upload-cache@v2
      with:
         path: ~/.ccache
         key: ${{ matrix.name }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
         restore-keys: |
           ${{ matrix.name }}-ccache-

    - name: Install BOOST (Linux)
      if: runner.os == 'Linux' && matrix.name != 'windows'
      run: |
        # Don't use weird boost version installed by github actions.
        sudo rm -rf /usr/local/share/boost

        # Maybe install a particular boost version.
        if [ -n "${{ matrix.install_boost }}" ] ; then
          sudo apt-get remove libboost-all-dev
          sudo add-apt-repository ppa:mhier/libboost-latest
          sudo apt-get update
          sudo apt-get install -y libboost${{ matrix.install_boost }}-dev
        else
          sudo apt-get install -y libboost-all-dev
        fi

    - name: Install BOOST and set up build (Windows meson cross compile)
      if: matrix.name == 'windows'
      env:
        USE_MPI: ${{ matrix.mpi }}
      run: |
        ${GITHUB_WORKSPACE}/projects/meson/make_winroot.sh -ccache true -gtk true
        ( cd ${GITHUB_WORKSPACE}/projects/meson/ ; ./generate.sh )
        
    - name: Update submodules
      run: |
        git submodule update --init --recursive
        
    - name: Configure and build
      if: matrix.name != 'windows'
      env:
        USE_MPI: ${{ matrix.mpi }}
        OSX_VERSION_MIN: "10.14"
      run: |
        if [ ${{ matrix.arch }} = "mac64" ] && [ -n "${OSX_VERSION_MIN}" ]; then
          MIN="-mmacosx-version-min=${OSX_VERSION_MIN}"
          export CFLAGS="$CFLAGS $MIN"
          export CXXFLAGS="$CXXFLAGS $MIN"
          export LDFLAGS="$LDFLAGS $MIN"
        fi

        cd projects/cmake
        ./build.sh -travis true -DCMAKE_INSTALL_PREFIX=$HOME/local
        cmake --install build

    - name: Configure and build (Windows meson cross compile)
      if: matrix.name == 'windows'
      env:
        BOOST_ROOT: /home/runner/win_root/mingw64/
      run: |
        PREFIX=${HOME}/local
        CXX=x86_64-w64-mingw32-g++-posix
        WINROOT=/home/runner/win_root
        /usr/local/bin/meson build ${GITHUB_WORKSPACE} --prefix=$PREFIX --cross-file=win64-cross.txt -Dopenlibm=true -Dstudio=true
        /usr/local/bin/ninja -C build install
        cp $($CXX --print-file-name libgcc_s_seh-1.dll)   $PREFIX/bin
        cp $($CXX --print-file-name libstdc++-6.dll)      $PREFIX/bin
        cp $($CXX --print-file-name libssp-0.dll)         $PREFIX/bin
        cp $($CXX --print-file-name libwinpthread-1.dll)  $PREFIX/bin
        cp $WINROOT/mingw64/bin/*.dll                     $PREFIX/bin
        cp $WINROOT/mingw64/bin/libopenlibm.dll           $PREFIX/bin
        # Don't put the wrapper in the same dir as rb.exe so we don't ship it
        mkdir $HOME/wrapper
        ( echo '#!/bin/bash'
          echo "cp $PREFIX/bin/* ."
          echo 'if [ "$#" -gt "1" ]; then'
          echo '  wine64 rb.exe ${@:1:$#-1} $(winepath -w ${@: -1} | sed "s,\\\\,\\\\\\\\,g")'
          echo 'else'
          echo '  wine64 rb.exe $(winepath -w ${1} | sed "s,\\\\,\\\\\\\\,g")'
          echo 'fi'
          echo 'rm -f *.exe'
          echo 'rm -f *.dll' ) > $HOME/wrapper/rb
        chmod +x ${HOME}/wrapper/rb

    - name: Test
      env:
        USE_MPI: ${{ matrix.mpi }}
        IS_WINDOWS: ${{ matrix.name == 'windows' }}
      run: |
        export PATH=${HOME}/wrapper:${HOME}/local/bin:$PATH

        echo "\"Hello World\"" | rb
        echo ::group::Test suite
        cd tests
        ./run_integration_tests.sh -mpi ${USE_MPI} -windows ${IS_WINDOWS} rb
        cd
        echo ::endgroup::
        echo ::group::testiphy
        git clone https://gitlab.com/testiphy/testiphy.git
        cd testiphy
        ./testiphy rb
        echo ::endgroup::

    - name: Upload test files if they failed
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-results-${{ matrix.name }}
        path: tests

    - name: Upload testiphy files if they failed
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: testiphy-results-${{ matrix.name }}
        path: '~/testiphy'

    - name: Get version
      id: get_version
      run: |
        echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Create tarball
      id: create_tarball
      run: |
        PREFIX=${HOME}/local
        PACKAGE=revbayes-${{ steps.get_version.outputs.version }}
        TAR=${PACKAGE}-${{ matrix.arch }}.tar.gz
        cp -a $PREFIX $PACKAGE
        tar -zcf $TAR ${PACKAGE}
        echo ::set-output name=archive::${TAR}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.create_tarball.outputs.archive }}
        asset_name: ${{ steps.create_tarball.outputs.archive }}
        asset_content_type: application/zip

  notify:
    name: Notify Slack
    needs: [build_singularity_and_upload, build_and_upload]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: technote-space/workflow-conclusion-action@v2.0.1
    - uses: 8398a7/action-slack@v3.8.1
      with:
        status: custom
        fields: workflow,commit,repo,ref,author
        custom_payload: |
          {
            username: 'action-slack',
            attachments: [{
              color: '${{ env.WORKFLOW_CONCLUSION }}' === 'success' ? 'good' : '${{ env.WORKFLOW_CONCLUSION }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR}: ${{ env.WORKFLOW_CONCLUSION }}`,
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
